1.Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import numpy as np

In [2]:
def Vandermonde(l,N):
    m = np.array(l)
    out = [np.array(pow(m,N))]
    try:
        N=N-2
        while N>=0:
            out = np.append(out, [pow(m,N)],axis=0)
            N=N-1
    except Exception as e:
        print("Exception : ",e)
    mat = np.mat(out)
    return mat.T
        

In [3]:
N=4
l = [1,2,3,5]
print(f'Input : {l}\n')
output = Vandermonde(l,N)
print(f'Output :\n {output}')

Input : [1, 2, 3, 5]

Output :
 [[  1   1   1   1]
 [ 16   4   2   1]
 [ 81   9   3   1]
 [625  25   5   1]]


In [36]:
x = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k =3

In [37]:
def m_avg(x,start,end):
    return np.average(np.array(x[start:end]))

In [38]:
start = 0
end = k
moving_average =[]
for i in range(0,len(x)-k+1):
    moving_average.append(m_avg(x,start,end))
    start+=1
    end+=1
print(moving_average)

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
